workflows:
  android-build:
    name: Android Build Workflow
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      # Step 1: Upgrade Gradle Wrapper to a compatible version
      - name: Upgrade Gradle Wrapper
        script: |
          echo "Upgrading Gradle wrapper to version 8.1.1"
          ./gradlew wrapper --gradle-version 8.1.1 --distribution-type all

      # Step 2: Install Android SDK Platform 35 (if not already installed)
      - name: Install Android SDK Platform 35
        script: |
          echo "Installing Android SDK Platform 35"
          yes | sdkmanager "platforms;android-35"

     
      # Step 4: Get Flutter dependencies
      - name: Get Flutter Dependencies
        script: |
          flutter pub get

      # Step 5: Build the APK in debug mode
      - name: Build APK
        script: |
          flutter build apk --debug

    artifacts:
      # Specify the path to the APK to be collected after the build
      - build/app/outputs/flutter-apk/app-debug.apk

